### ISSUE TITLE
BTC fee need to be configurable

### ISSUE THREAD

**Issue by bayk** [mwcproject/swapsite#15]
Currently BTC fee is always 10 satoshi per byte.  Units are good, but user will need to be able to control this value.
fee_satoshi_per_byte  need to be passed for actions that creating and posting BTC transaction.  Probably will be done as a swap config API. 

Make sure that report issues is covered with that as well.

**Comment by cgilliard** [comment]
Should show the fees to user as part of the output of the trade.

**Comment by bayk** [comment]
Testing results for secondary_fee_per_byte value 1.2:
> mwc-wallet --floonet swap --process -a publish_BTC  -i cc1fbb95-f71d-45fd-b63c-15f125ce9473 --secondary_fee_per_byte 1.2


Waiting for BTC Redeem transaction to be confirmed for 67cc0b725b07ba25c4b0ba25393a11be4ed0ac0c752b76b34b04369354b38d3a


Here is transaction details:  https://blockstream.info/testnet/tx/67cc0b725b07ba25c4b0ba25393a11be4ed0ac0c752b76b34b04369354b38d3a


![image](https://user-images.githubusercontent.com/42393608/87235902-80b3d000-c396-11ea-860e-a1f1575ff924.png)


Resulting fee matching expected value.
