### ISSUE TITLE
Add Transports for messages

### ISSUE THREAD

**Issue by bayk** [mwcproject/swapsite#20]
Currently 'action' command had 'method' and 'destination'. In current prototype it is always a file. Need to be able to support any transport including files.

Send must not duplicate the code.  mwc-wallet at 'send' command does the similar, we need to reuse that code because of it complexity.

Listeners need to be added. If message arrive, it should be processed with owner API that already exist and works great.

**Comment by hcasalet** [comment]
Added support for transport through MQS and TOR.
