### ISSUE TITLE
Autoswap shouldn't in CLI mode should not manage listeners, should check if needed listener is running

### ISSUE THREAD

**Issue by bayk** [mwcproject/swapsite#40]
The use case should be supported:
$  mwc-wallet cli
listen -m mwcmqs
listen -m tor
starting autoswap with MQS destination address.
starting  autoswap with TOR destination address
 starting autoswap with anoher MQS destination address.
starting  autoswap with another TOR destination address

In order to achieve that, autoswap need to start listener if it is not running. Listeners already have a flags/methods that allow to detect that fact.  autoswap need to start them if they are offline.

**Comment by hcasalet** [comment]
Now by default auto-swap will not start listeners, so starting listeners through an explicit "listen" will be supported. Also, one can specify on the command to start auto-swap with --start_listener to start it.
