### ISSUE TITLE
BCH/BTC support

### ISSUE THREAD

**Issue by electrum17** [mwcproject/swapsite#46]
For the first release, let's support BCH only, but have BTC ready. We need to separate the electrum_node_parameter into:
electrumx_btc_node_addr and electrumx_bch_node_addr. In the mwc-wallet, the commands should allow for separate swaps of BTC/MWC and BCH/MWC. The only difference is that a different electrumx node is used. In the first release, let's make BTC disabled, so when you do the commands for BTC, it will return an error that says BTC is not supported, but then on the second release, we'll remove the error messages and make BTC or BCH work. This will require all messages that include BTC to be updated for example in the help and other error messages.

**Comment by hcasalet** [comment]
Enabled the support of BCH.
