### ISSUE TITLE
Swap Objects Serialization need to be encrypted

### ISSUE THREAD

**Issue by bayk** [mwcproject/swapsite#8]
Even there is no private keys, data is sensitive. We should encode it with a wallet's  seed secret (use derivative key, not a root secret).

Because it is saved/loaded as a string, there should be no problem to do that.

**Comment by bayk** [comment]
Swaps serialization location    mwc-wallet/libwallet/src/swap/trades.rs

Also please add command that dump Swap data content to the console in json format, so we will be able to debug.

**Comment by hcasalet** [comment]
Working on it....

**Comment by hcasalet** [comment]
Added encrypting swap object+context, and decrypting stored encrypted swap file content.
Added "swap --dump -i <swap_id>" command. 

Tests done: Manually verified the swap file stored is encrypted. Also "swap --check" returns correct result; "swap --dump" dumps the decrypted swap object and swap context. 

Cargo test --all: runs clean.
